kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: golang:1.16
    commands:
      - ./scripts/rancher-release.sh
  - name: github_binary_release
    image: plugins/github-release:linux-amd64
    settings:
      api_key:
        from_secret: github_token
      files:
        - release/portmap-amd64
        - release/portmap-arm64
        - release/portmap-arm
    when:
      instance:
        - drone-publish.rancher.io
      event: tag
